name: Maven Build and Publish
on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build with Maven
      run: mvn clean package

    - name: Get JAR Location
      run: |
        jar_location=$(find target -name '*.jar' -exec readlink -f {} +)
        echo "JAR Location: $jar_location"
        echo "::set-output name=jar_location::$jar_location"
      id: jar


    - name: Create Snapshot
      id: snapshot
      run: |
        timestamp=$(date "+%Y%m%d%H%M%S")
        jar_location=$(find target -name '*.jar' -exec readlink -f {} +)
        snapshot_name="${jar_location%.*}-SNAPSHOT-${timestamp}.jar"
        cp "$jar_location" "$snapshot_name"
        echo "Snapshot created: $snapshot_name"
        echo "::set-output name=snapshot_name::$snapshot_name"


    - name: Deploy Snapshot
      run: |
        snapshot_location="${{ steps.snapshot.outputs.snapshot_name }}"
        echo "$snapshot_location"

    - name: Jfrog push v2
      uses: jfrog/setup-jfrog-cli@v2
      env:
        JF_URL: http://13.201.130.85:8081
        JF_USER: admin
        JF_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
    - run: |
        jf rt u "target/github-action-maven-tutorial-1.0-SNAPSHOT.jar" "jfrog/github-action-maven-tutorial/1.0-SNAPSHOT/github-action-maven-tutorial-1.0-SNAPSHOT.jar"
